server:
  port: 8093

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

## 动态线程池管理配置
#dynamic:
#  thread:
#    pool:
#      config:
#        # 状态；true = 开启、false 关闭
#        enabled: true
#        # redis host
#        host: 139.224.188.112
#        # redis port
#        port: 6379
#        password: 123456

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml